//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmbracoPublic.WebSite.masterpages {
    
    
    public partial class GeneralPage {
        
        /// <summary>
        /// breadCrumb control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UmbracoPublic.Logic.Parts.Navigation.BreadCrumbPart breadCrumb;
        
        /// <summary>
        /// sideNavigation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UmbracoPublic.Logic.Parts.Navigation.SideNavigationPart sideNavigation;
        
        /// <summary>
        /// plhTop control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LinqIt.UmbracoCustomFieldTypes.GridModulePlaceholder plhTop;
        
        /// <summary>
        /// generalContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UmbracoPublic.WebSite.usercontrols.Parts.GeneralContentPart generalContent;
        
        /// <summary>
        /// plhMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LinqIt.UmbracoCustomFieldTypes.GridModulePlaceholder plhMain;
        
        /// <summary>
        /// plhRight control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LinqIt.UmbracoCustomFieldTypes.GridModulePlaceholder plhRight;
        
        /// <summary>
        /// plhBottom control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LinqIt.UmbracoCustomFieldTypes.GridModulePlaceholder plhBottom;
    }
}
