//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmbracoPublic.WebSite.masterpages {
    
    
    public partial class NewsListPage {
        
        /// <summary>
        /// searchResultPart control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UmbracoPublic.WebSite.usercontrols.Parts.NewsSearchResultPart searchResultPart;
        
        /// <summary>
        /// searchFilterPart control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UmbracoPublic.WebSite.usercontrols.Parts.NewsSearchFilterPart searchFilterPart;
    }
}
