//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmbracoPublic.WebSite.masterpages {
    
    
    public partial class TwoColumnWidePage {
        
        /// <summary>
        /// SubNavigationBar1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UmbracoPublic.WebSite.usercontrols.Parts.SubNavigationBar SubNavigationBar1;
        
        /// <summary>
        /// plhTop control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LinqIt.UmbracoCustomFieldTypes.GridModulePlaceholder plhTop;
        
        /// <summary>
        /// plhCol1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LinqIt.UmbracoCustomFieldTypes.GridModulePlaceholder plhCol1;
        
        /// <summary>
        /// plhCol2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LinqIt.UmbracoCustomFieldTypes.GridModulePlaceholder plhCol2;
        
        /// <summary>
        /// plhBottom control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LinqIt.UmbracoCustomFieldTypes.GridModulePlaceholder plhBottom;
    }
}
