//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmbracoPublic.Logic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UmbracoPublic.Logic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%@ Control Language=&quot;C#&quot; AutoEventWireup=&quot;true&quot; CodeBehind=&quot;MODULE_NAMERendering.ascx.cs&quot; Inherits=&quot;UmbracoPublic.WebSite.modules.MODULE_NAMERendering, UmbracoPublic.WebSite&quot; %&gt;
        ///.
        /// </summary>
        internal static string ModuleAscxTemplate {
            get {
                return ResourceManager.GetString("ModuleAscxTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Web;
        ///using System.Web.UI;
        ///using System.Web.UI.WebControls;
        ///using LinqIt.Utils.Web;
        ///using UmbracoPublic.Logic.Entities;
        ///
        ///namespace UmbracoPublic.WebSite.modules
        ///{
        ///    public partial class MODULE_NAMERendering : BaseModule&lt;MODULE_NAME&gt;
        ///    {
        ///        protected void Page_Load(object sender, EventArgs e)
        ///        {
        ///
        ///        }
        ///
        ///        protected override void RenderModule(MODULE_NAME module, LinqIt.Utils.Web.HtmlWriter writer)
        ///        { [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModuleCodeTemplate {
            get {
                return ResourceManager.GetString("ModuleCodeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///
        ///namespace UmbracoPublic.WebSite.modules
        ///{
        ///
        ///
        ///    public partial class MODULE_NAMERendering
        ///    {
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string ModuleDesignerTemplate {
            get {
                return ResourceManager.GetString("ModuleDesignerTemplate", resourceCulture);
            }
        }
    }
}
